on:
    push:
    pull_request:

jobs:
    build:
        runs-on: windows-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 17

            - uses: gradle/gradle-build-action@v3
              with:
                  gradle-version: 8.14.3

            - run: gradle assembleDebug

            - uses: actions/upload-artifact@v4
              with:
                  name: debug-apk
                  path: app/build/outputs/apk/debug/*.apk

            - uses: softprops/action-gh-release@v2
              with:
                  # tag_name: "build-${{ github.run_number }}"
                  tag_name: ${{ github.sha }}
                  files: app/build/outputs/apk/debug/app-debug.apk
